name: Build Release

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Distributions
        run: |
          set -e
          ./gradlew distTar distZip

      - name: Get Project Version
        id: version
        run: echo "VERSION=$(./gradlew printVersion -q)" >> $GITHUB_ENV

      - name: Debug Project Version
        run: |
          echo "VERSION: ${{ env.VERSION }}"

      - name: Verify Distributions
        run: |
          ls -l build/distributions
          test -f build/distributions/Chromagica-${{ env.VERSION }}.tar
          test -f build/distributions/Chromagica-${{ env.VERSION }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: "Release of version ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .tar Asset
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/distributions/Chromagica-${{ env.VERSION }}.tar
          asset_name: Chromagica-${{ env.VERSION }}.tar
          asset_content_type: application/x-tar

      - name: Upload .zip Asset
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/distributions/Chromagica-${{ env.VERSION }}.zip
          asset_name: Chromagica-${{ env.VERSION }}.zip
          asset_content_type: application/zip
